//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: azurebatch_http_proxy.proto
namespace Org.Apache.REEF.Common.Protobuf.ReefProtocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HttpProxyRequestProto")]
  public partial class HttpProxyRequestProto : global::ProtoBuf.IExtensible
  {
    public HttpProxyRequestProto() {}
    
    private string _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _endpoint = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"endpoint", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string endpoint
    {
      get { return _endpoint; }
      set { _endpoint = value; }
    }
    private string _responseQueue = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"responseQueue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string responseQueue
    {
      get { return _responseQueue; }
      set { _responseQueue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HttpProxyResponseProto")]
  public partial class HttpProxyResponseProto : global::ProtoBuf.IExtensible
  {
    public HttpProxyResponseProto() {}
    
    private string _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _responseCode = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"responseCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int responseCode
    {
      get { return _responseCode; }
      set { _responseCode = value; }
    }
    private string _responseBody = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"responseBody", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string responseBody
    {
      get { return _responseBody; }
      set { _responseBody = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}